version: "3.9"
services:
  image:
    build: .
    image: homecentr/frigate:preview
    user: 1000:1000
    read_only: true
    depends_on:
      - mqtt
    networks:
      internal:
    ports:
      - "5000:5000"
      - "1935:1935"
    volumes:
      - "./example/frigate.yml:/config/config.yml:ro"
    tmpfs:
      - /tmp
      - /media/frigate

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "./example/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    networks:
      internal:

networks:
  internal:
    driver: bridge